name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          payloads:
            - 'app/services/gamebridge/payloads/structures/**'
    - name: normal deploy
      if: steps.filter.outputs.payloads == 'false'
      uses: fjogeleit/http-request-action@v1
      with:
        # Request URL
        url: https://metaconcord.metastruct.net/ci/reload
        # Request Method
        method: GET
        bearerToken: ${{secrets.TOKEN}}
    - name: deploy all
      if: steps.filter.outputs.payloads == 'true'
      uses: fjogeleit/http-request-action@v1
      with:
        # Request URL
        url: https://metaconcord.metastruct.net/ci/reload?all=true
        # Request Method
        method: GET
        bearerToken: ${{secrets.TOKEN}}