name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          # Request URL
          url: https://g2.metastruct.net/metaconcord/ci/reload
          # Request Method
          method: GET
          bearerToken: ${{secrets.TOKEN}}